{
 "title": "Daemonset-Dashbaord",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_daemonset_status_desired_number_scheduled{namespace=\"ops\"},namespace)"
    }
   },
   {
    "name": "daemonset",
    "label": "DaemonSet",
    "query": {
     "query": "label_values(kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\"},daemonset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$daemonset-.*\", container!=\"POD\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$daemonset-.*\", container!=\"POD\"}[5m]))",
     "legendFormat": "CPU Usage (cores)"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$daemonset-.*\"}[5m]) + rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$daemonset-.*\"}[5m]))",
     "legendFormat": "Network I/O"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Desired Replicas"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Available Replicas"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_observed_generation{namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Observed Generation"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_metadata_generation{namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_daemonset_status_number_available{namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Avaliable"
    }
   ]
  }
 ]
}