{
 "title": "Kubernetes Deployment Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$deployment.*\", phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\",container!=\"POD\", container!=\"\"} /1024/1024",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}/1024",
     "legendFormat": "CPU Usage (cores)"
    }
   ]
  },
  {
   "title": "Memory Usage per Deployment (Aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"POD\", container!=\"\"}) by (deployment)",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage per Deployment (Aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"POD\", container!=\"\"}[5m])) by (deployment) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Network I/O per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "Network Receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "Network Transmit"
    }
   ]
  },
  {
   "title": "Disk I/O per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m])",
     "legendFormat": " read"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m])",
     "legendFormat": " write"
    }
   ]
  }
 ]
}