{
 "title": "Kafka Database-Dashbaord",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values()" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"kafka\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(avg_over_time(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$deployment-.*\",container!=\"\",container!=\"POD\"}[$__range]) )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{\r\n  namespace=\"kafka\",\r\n  pod=\"$pod\",\r\n  container!=\"\",\r\n  image!=\"\"\r\n}) / 1024 / 1024",
     "legendFormat": "Memory working"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{\r\n  namespace=\"kafka\",\r\n  pod=\"$pod\",\r\n  container!=\"\",\r\n  image!=\"\"\r\n}[5m])) ",
     "legendFormat": "Cpu Usage"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m])\r\n  +\r\n  rate(container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m])\r\n) / 1024 / 1024\r\n",
     "legendFormat": "Network I/O"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Receive & Transmit MB/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod)(\r\n  rate (container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m])\r\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage and Limits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"kafka\",persistentvolumeclaim=\"data-0-kafka-cluster-dual-role-0\"})/1024/1024\r\n",
     "legendFormat": "Limits"
    },
    {
     "expr": "(\r\n  sum(kubelet_volume_stats_capacity_bytes{namespace=\"kafka\",persistentvolumeclaim=\"data-0-kafka-cluster-dual-role-0\"})\r\n-\r\nsum(kubelet_volume_stats_used_bytes{namespace=\"kafka\",persistentvolumeclaim=\"data-0-kafka-cluster-dual-role-0\"})\r\n) / 1027 / 1027",
     "legendFormat": "avaliable"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"kafka\",persistentvolumeclaim=\"data-0-kafka-cluster-dual-role-0\"})/ 1027 / 1027",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}