{
 "title": "MongoDB Database-Dashbaord",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values()" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"mongodb\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(avg_over_time(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$deployment-.*\",container!=\"\",container!=\"POD\"}[$__range]) )"
    }
   },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{namespace=\"$namespace\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MongoDB Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mongodb_up)", "legendFormat": "UP" }
   ]
  },
  {
   "title": "Active MongoDB Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_connections{conn_type=\"active\"})",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Current MongoDB Connections ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_connections{conn_type=\"current\"})",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "MongoDB Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_connections{conn_type=\"available\"})",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "MongoDB Idle Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_connections{conn_type=\"current\"})\r\n-\r\nsum(mongodb_ss_connections{conn_type=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{\r\n  namespace=\"mongodb\",\r\n  pod=\"$pod\",\r\n  container!=\"\",\r\n  image!=\"\"\r\n}) / 1024 / 1024\r\n",
     "legendFormat": "Memory working"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{\r\n  namespace=\"mongodb\",\r\n  pod=\"$pod\",\r\n  container!=\"\",\r\n  image!=\"\"\r\n}[5m]))\r\n",
     "legendFormat": "Cpu Usage"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m])\r\n  +\r\n  rate(container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m])\r\n) / 1024 / 1024\r\n",
     "legendFormat": "Network I/O"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Receive & Transmit MB/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m]))/1024/1024",
     "legendFormat": "Network Received Per Second"
    },
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\", interface!~\"lo|veth.*\"}[5m])\r\n) / 1024 / 1024",
     "legendFormat": "Network Transmitted Per Second"
    }
   ]
  },
  {
   "title": "MongoDB Ops per Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"query\"}[5m])",
     "legendFormat": "Qureies per second"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"insert\"}[5m])",
     "legendFormat": "Insert per second"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"update\"}[5m])",
     "legendFormat": "Updates per second"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"delete\"}[5m])",
     "legendFormat": "Delete per second"
    }
   ]
  },
  {
   "title": "Disk Usage and Limits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"mongodb\",persistentvolumeclaim=\"$pvc\"}) /1026/1026\r\n",
     "legendFormat": "Limits"
    },
    {
     "expr": "(\r\n  sum(kubelet_volume_stats_capacity_bytes{namespace=\"mongodb\", persistentvolumeclaim=\"$pvc\"})\r\n-\r\n  sum(kubelet_volume_stats_used_bytes{namespace=\"mongodb\", persistentvolumeclaim=\"$pvc\"})\r\n) / 1027 / 1027",
     "legendFormat": "avaliable"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"mongodb\",persistentvolumeclaim=\"$pvc\"}) /1027/1027",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}