{
 "title": "PgBouncer Database dashboard",
 "description": "Pgbouncer dashboard for Grafana integrated with Percona PMM as well.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "pgbouncer_up" },
   { "name": "env", "label": "Environment", "query": "Dev,Prod" },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pgbouncer_databases_current_connections,database)"
    }
   },
   { "name": "node", "label": "Node Name", "query": "process_start_time_seconds" }
  ]
 },
 "panels": [
  {
   "title": "pgbouncer status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_up{node_ip=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "stat",
   "description": "Maximum connections to Postgres Database",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (database,hostname) (pgbouncer_databases_pool_size{database=~\"$database\",node_ip=~\"$host\"})\r\n"
    }
   ]
  },
  {
   "title": "Max DB Conn",
   "type": "stat",
   "description": "Maximum number of allowed connections per-database",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_max_connections{database=~\"$database\",node_ip=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Client Conn",
   "type": "stat",
   "description": "Maximum number of allowed connections per-database",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_config_max_client_connections{node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max User Conn",
   "type": "stat",
   "description": "Maximum number of allowed connections per-database",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_config_max_user_connections{node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{node_name=\"$node\"} * 1000"
    }
   ]
  },
  {
   "title": "Active Client Connections",
   "type": "gauge",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=\"$database\"})"
    }
   ]
  },
  {
   "title": "Current conn on DB",
   "type": "gauge",
   "description": "Total number of per-database Database connections count",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_current_connections{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Server Used Conn",
   "type": "gauge",
   "description": "Server connections that have been idle for more than `server_check_delay`, so they need `server_check_query` to run on them before they can be used again.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_server_used_connections{database=\"$database\",node_ip=\"$host\"})"
    }
   ]
  },
  {
   "title": "Server Idle",
   "type": "gauge",
   "description": "Server connections that are unused and immediately usable for client queries.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_server_idle_connections{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Server Tested Conn",
   "type": "gauge",
   "description": "Server connections that are currently running either `server_reset_query` or `server_check_query`.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_server_testing_connections{database=\"$database\",node_ip=\"$host\"})"
    }
   ]
  },
  {
   "title": "Exporter Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{node_name=\"$node\"})"
    }
   ]
  },
  {
   "title": "Clients Active",
   "type": "timeseries",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=\"$database\"})",
     "legendFormat": "Active clients"
    }
   ]
  },
  {
   "title": "Client Waiting",
   "type": "timeseries",
   "description": "How long the first (oldest) client in queue has waited, in seconds",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_maxwait_seconds{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "User: {{user}}"
    }
   ]
  },
  {
   "title": "Exporter CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{node_name=~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total SQL Transactions Pooled",
   "type": "stat",
   "description": "Total number of SQL transactions pooled by pgbouncer",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_sql_transactions_pooled_total{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Active Client Connections(Per User)",
   "type": "bargauge",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user)(pgbouncer_pools_client_active_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Client Connections(Per User)",
   "type": "bargauge",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer_pools_server_idle_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Queries Pooled",
   "type": "stat",
   "description": "Total number of SQL queries pooled by pgbouncer",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_queries_pooled_total{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Server Conn Logging in process",
   "type": "timeseries",
   "description": "Server connections currently in logging in process",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_server_login_connections{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "User: {{user}}"
    }
   ]
  },
  {
   "title": "Queries Duration",
   "type": "stat",
   "description": "Total number of microseconds spent waiting for a server to return a query response. Includes time spent waiting for an available connection.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_queries_duration_seconds_total{database=\"$database\",node_ip=\"$host\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Waiting",
   "type": "stat",
   "description": "Total number of microseconds spent waiting for an available connection",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_client_wait_seconds_total{database=\"$database\",node_ip=\"$host\"} / 1000000",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Waiting for Server Conn",
   "type": "timeseries",
   "description": "Client connections have sent queries but have not yet got a server connection",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$database\",node_ip=~\"$host\"}",
     "legendFormat": "user: {{user}}"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes",
   "type": "timeseries",
   "description": "Total volume in bytes of network traffic sent / received by pgbouncer",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc( sum by (database,hostname) ( rate(pgbouncer_stats_totals_received_bytes_total{database=~\"$database\",node_ip=~\"$host\"}[1m])*8 ) )",
     "legendFormat": "{{ database }}: Stats received bytes total"
    },
    {
     "expr": "sort_desc( sum by (database,hostname) ( rate(pgbouncer_stats_totals_sent_bytes_total{database=~\"$database\",node_ip=~\"$host\"}[1m])*8 ) )",
     "legendFormat": "{{ database }}: Stats sent bytes total"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"ADMIN_DEV\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}