apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki-stack
  namespace: ops
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: ops
spec:
  chart:
    spec:
      chart: loki-stack
      version: '2.10.2'
      sourceRef:
        kind: HelmRepository
        name: loki-stack
  interval: 2m0s
  releaseName: loki-stack
  timeout: 600s