apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 1m0s
  url: https://charts.fairwinds.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks-release
  namespace: goldilocks
spec:
  chart:
    spec:
      chart: goldilocks
      version: '9.0.0'
      sourceRef:
        kind: HelmRepository
        name: goldilocks
  interval: 1m0s
  releaseName: goldilocks-release