apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  interval: 10m
  url: https://provectus.github.io/kafka-ui-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  interval: 10m
  chart:
    spec:
      chart: kafka-ui
      version: "0.7.6"
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: kafka
  values:
    replicaCount: 1
    image:
      repository: provectuslabs/kafka-ui
      tag: latest
    env:
      - name: KAFKA_CLUSTERS_0_NAME
        value: strimzi
      - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        value: kafka-cluster-kafka-bootstrap.kafka:9092
    service:
      type: ClusterIP
      port: 8080