apiVersion: v1
kind: Namespace
metadata:
  name: netbird
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
type: Opaque
data:
  NB_API_KEY: ##ADD_YOUR_BASE64_ENCODED_API_KEY_HERE##
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: netbirdio
  namespace: netbird
spec:
  interval: 1m0s
  url: https://netbirdio.github.io/kubernetes-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbird-release
  namespace: netbird
spec:
  chart:
    spec:
      chart: kubernetes-operator
      version: '0.1.13'
      sourceRef:
        kind: HelmRepository
        name: netbirdio
  interval: 1m0s
  releaseName: netbird-release
  values: 
    ingress:
      enabled: true
    router:
      enabled: true

    netbirdAPI:
      keyFromSecret:
        name: "netbird-mgmt-api-key"   # <-- name of your Kubernetes Secret
        key: "NB_API_KEY"              # <-- key inside the secret
      key: "NB_API_KEY"                # <-- must match the key used inside the Secret