apiVersion: v1
kind: Namespace
metadata:
  name: solr
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-oci-solr
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/solr
  ref:
    semver: "9.6.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: solr-release
  namespace: solr
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-oci-solr
    namespace: flux-system
  interval: 10m
  values:
    global:
      security:
        allowInsecureImages: true
    image: 
      repository: bitnamilegacy/solr
    zookeeper: 
      global:
        security:
          allowInsecureImages: true
      image: 
        repository: bitnamilegacy/zookeeper